server:
  port: 8087

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: root

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  output:
    ansi:
      enabled: always
  application:
    name: ead-authuser-service

logging:
  level:
    com.ead: trace
    root: info
    org.springframework.web: debug
    org.hibernate: info

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

  instance:
    hostname: localhost

ead:
  api:
    url:
      course: 'http://ead-course-service'