server:
  port: 8087

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: admin

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  output:
    ansi:
      enabled: always

logging:
  level:
    com.ead: trace
    root: info
    org.springframework.web: debug
    org.hibernate: info